#! /bin/sh
set -e
#***************************************************************************************#
#											#
# Insert Folding section in GRUB configuration file					#
# (c) aso, v.1.4.9 by 23.01.2013.							#
#   GPLv3										#
#											#
# -t, --pipline           processing input file (stdin) into stdout output file		#
# -i, --in-place          processing config file "in place" from stdout; default option	#
#											#
#***************************************************************************************#


ver='1.4.9'
version="$ver, by 23.01.2013 from aso"

gen='gen'
win='win'

sysconfdir="/etc"
grub_mkcfg_dir="${sysconfdir}/grub.d"

self=`basename $0`
GRUB_PREFIX=`echo '/boot/grub' | sed "s,//*,/,g"`

tmpdir='/tmp'
tmprefix="$tmpdir/fold$$$"

# Calling from folding marker 
_infolding='Yes'
export _infolding



BEG='BEGIN'
EN='END'



usage()
{
    cat <<EOF
Usage: $self [OPTION]
Insert Folding section in GRUB configuration file

  -t, --pipline           processing input file (stdin) into stdout output file
  -i, --in-place          processing config file "in place" from stdout; default option

###Report bugs to <bug-grub@gnu.org>.
EOF
} # usage() --------------------------------------


# Create marker
mark() {
local MARK='###'
echo "$MARK\ $1\ $MARK"
} # mark() ---------------------------------------


# Generate section file name
# Parameters:
#   #1 - prefix, OS_name (gentoo, win),
#   #2 - tail {prolog | epilog}
sect_fn() {
echo "_$1-$2"
} # sect_fn() ------------------------------------


# Echoing OS name from class
# Parameter:
#   #1 - class OS (gentoo, win),
o_name()
{
case "$1" in
'win')	  echo 'Microsoft Windows'
	;;
'gentoo') echo 'Gentoo Linux'
	;;
'gen')	  echo 'Gentoo Linux'
	;;
esac
} # o_name() -------------------------------------


# Create full format marker string
# Paramatars:
#   $1 - 'BEGIN' / 'END'
#   $2 - full file name
fullmark()
{
sed 's/\//\\&/'g <<EOF
$(mark "$1\ $grub_mkcfg_dir/$2")
EOF
} # fullmark() -----------------------------------




p='prolog'
e='epilog'

# Insert section in config file function
# Parameters:
#   $1 - OS class
remark_insert()
{
## control string for sed for search control comment: '### Begin...' & insert file name
echo "
/$(fullmark $BEG $(sect_fn $1 $p))/ r $(sect_fn $1 $p)
/$(fullmark $BEG $(sect_fn $1 $e))/ r $(sect_fn $1 $e)
"
} # remark_insert()------------------------------------------------------------


# Insert folding section in config file function
# Parameters:
#   $1 - OS class (win/gentoo)
#   $2 - sect class (prolog/epilog)
remark_insert2()
{
## control string for sed for search control comment: '### Begin...' & insert file name
#echo "
#/$(mark "BEGIN\ $(echo $(sect_fn $1 $p)| sed 's/\//\\&/'g)")/ r $(sect_fn $1 $p)
#/$(mark "BEGIN\ $(echo $(sect_fn $1 $e)| sed 's/\//\\&/'g)")/ r $(sect_fn $1 $e)
#"
echo "
/$(fullmark $BEG $(sect_fn $1 $2))/! b end

n
/$(fullmark $EN $(sect_fn $1 $2))/! end
i \\
$($grub_mkcfg_dir/$(sect_fn $1 $2) | sed 's/\\/\\\\/g; s/[#; {}//]/\\&/g; $!s/.$/&\\/g')

:end
"
} # remark_insert2()-----------------------------------------------------------


# Safe string
safe="!!!Reserved!!!"

# Insert folding section in config file function
# on file insertion & full control of output (-n option)
# Parameters:
#   $1 - OS class (win/gentoo)
#   $2 - sect class (prolog/epilog)
final_mark()
{
${grub_mkcfg_dir}/$(sect_fn $1 $2) > "$tmprefix$(sect_fn $1 $2)"
sed -e "/$(fullmark $BEG $(sect_fn $1 $2))${safe}/ {
r $tmprefix$(sect_fn $1 $2)
s/${safe}//
}"
rm -f "tmprefix$(sect_fn $1 $2)"
} # final_mark()---------------------------------------------------------------



# Echoing string for varkup section in config file function
# Parameters:
#   $1 - OS class (gen, win...)
echo_remark()
{

echo "
/\([^#]*.*menuentry\)\([^#].*$(o_name $1)\)/! b end  # detect start of section /menuentry <OS_Name>/

i\\
\\\n$(fullmark $BEG $(sect_fn $1 $p))$safe
i\\$(fullmark $EN $(sect_fn $1 $p))\\\n

:consect		# continue sampling section
n
/^}/! b consect

:interch		# final of section. Sampling iterval between sections
n
/[^#]*.*menuentry/ {	# detect new section
/[^#]*.*$(o_name $1)/ b consect	# new section is desired
b close			# new section is not desired
}
/### \($BEG\)\|\($EN\)/ b close	# detect new section, marked by control comments
b interch

:close

i\\
\\\n$(fullmark $BEG $(sect_fn $1 $e))$safe
i\\$(fullmark $EN $(sect_fn $1 $e))\\\n

:end
"

} # echo_remark() -------------------------------------------------------------------------




# Processing the arguments.
while test $# -gt 0
do
    option=$1
    shift

    case "$option" in
    -h | --help)
	usage
	exit 2 ;;
    -v | --version)
#	echo "$self (${PACKAGE_NAME}) ${PACKAGE_VERSION}"
	echo $version
	exit 0 ;;
    -t | --pipeline)
	pipe=${option} ;;
    -i | --in-place)
	pipe='' ;;
    -*)
	allopts="$allopts $option"
	;;
    # Explicitly ignore non-option arguments, for compatibility.
    esac
done


echo "Folding ($ver) ..." >&2

echo "# Folding $version"
echo "# This is a stub"
echo "# Output of this module was placed bypass the main flow"


if ! [ $pipe ] ; then

  tmpbuf='/tmp/$$$sect$$$'
  exec 4<&0	# store stdin into #4
  exec 6>&1	# store stdout into #6
  outfile=$(readlink /proc/self/fd/6)
  set -- $(du -b $outfile); fsz1=$1
  exec 1>&-		# close stdout
  exec 0< $outfile
  exec 1> $tmpbuf

fi


##************##
sed $allopts -e "$(echo_remark $win)" |
# sed $allopts -e "$(remark_insert $win)" |
 final_mark $win $p | final_mark $win $e |
 sed $allopts -e "$(echo_remark $gen)" |
# sed $allopts -e "$(remark_insert $gen)"
 final_mark $gen $p | final_mark $gen $e
##************##


if ! [ $pipe ] ; then
	#restore all files
  exec 1>&-		# close stdout
  exec 0<&-		# close stdin
  set -- $(du -b $tmpbuf); fsz2=$1
  cat $tmpbuf > $outfile
  exec 0<&4
  exec 1>&6
  tail -c $(($fsz2 - $fsz1)) $tmpbuf
  rm "$tmpbuf"	# remove tmpbuf

fi
