#! /bin/sh
set -e
####################################################
#
# launch the Sectioneer for debug
# v.0.4.0 from 29.12.2012. by aso
#
#
####################################################

sysconfdir="/etc"
grub_mkconfig_dir="${sysconfdir}"/grub.d

self=`basename $0`
GRUB_PREFIX=`echo '/boot/grub' | sed "s,//*,/,g"`


in_cfg='bbb1'
#in_cfg='bbb2'
out_cfg='bbb'
placeopt='--in-place'



###############
echo "exec ./test.sh" >&2
#./sectioneer $placeopt >>$out_cfg
#./sectioneer $placeopt
#./folding $placeopt
./test.sh < $in_cfg
###################

