#! /bin/bash

#
# Generate Section files with specified parameters
# Copyright (c) aso, v.0.1, 14.07.14

# trap 'echo Process terminated' TERM
# trap 'echo Process interrupted' INT
# trap -p

#trap TERM # посылается kill без спецификации сигнала; при завершении выдаёт "завершено"

# echo 'TERMinate!' && kill -s TERM $$
# echo 'INTerrupt!' && kill -s INT $$


_dev=1
export _dev

. ./folding

sec_auth='aso'
sec_date='14.07.2014'
sec_ver='2.1.0'

sec_os=( 'gen', 'win' )
sec_os_full=( 'Gentoo', 'Windows' )
sec_hdr=( 'Gentoo Linux (all vaiants)', 'submenu "MS Windows (all variants)" {' )

mk-sect()
{
    cat << COFR
#! /bin/sh
set -e

## grub-mkconfig helper script.
## Copyright (C) 2006,2007,2008,2009,2010  Free Software Foundation, Inc.
##
## GRUB is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## GRUB is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with GRUB.  If not, see <http://www.gnu.org/licenses/>.

####################################################
#
# Gentoo section prologue GRUB configuration file
# Gentoo section ${2}logue GRUB configuration file
# v.${sec_ver} from ${sec_date}. by ${sec_auth}
#
# -i, --insert            insert section data into stdout
# -x, --exclude           exclude folding header
# -h, --help              print this message and exit
# -v, --version           print the version information and exit
#
####################################################

ver='${sec_ver}'
date='${sec_date}'
version="v.\$ver, from \$date by ${sec_auth}"


usage()
{
    cat <<EOF
_gen-prolog: grub-mkconfig helper script.
_${1}-${2}log: grub-mkconfig helper script.
version \$version
Insert Gentoo section prologue into GRUB configuration file
Insert Gentoo section ${2}logue into GRUB configuration file
Usage: _gen-prolog [OPTIONS]
Usage: _${1}-${2}log [OPTIONS]

  -i, --insert            output section data into stdout
  -x, --exclude           exclude folding header
  -h, --help              print this message and exit
  -v, --version           print the version information and exit

Combined short options are allowed.
EOF
} # usage() --------------------------------------

_insert=0
_exclude=0

# Processing the arguments.
while getopts hvix f
do
    case $f in
    h | --help)
	usage
	exit 2 ;;
    v | --version)
	echo $version
	exit 1 ;;
    i | --insert)
	_insert=1
	;;
    x | --exclude)
	_exclude=1
	;;
    esac
done
shift $(($OPTIND - 1))

# Don't change the next "if" operator
if [ ${_insert} = 0 ] ; then
  echo "# This is a gentoo section prologue stub"
  echo "# $version"
  exit
fi


echo "Start Gentoo folding section in menu" >&2

# User code section 1 >>>------------------------
# Insert user code here, between this lines, code placed out of section, before section header

# End of user code section <<<-------------------

# Insert Gentoo section header if nedeed
if  [ "${_exclude}" = 0 ] ; then
    echo 'submenu "Gentoo Linux (all vaiants)" {'
fi

# User code section 2 >>>------------------------
# Insert user code below this line, code placed in section after header >>>-----------------

# My insertion - aso
# Gentoo section - Universal entry from Gentoo Legacy Grub
cat << EOF
# Custom entry for the own Gentoo Legasy GRUB booting.
menuentry "Gentoo Linux (all variants, on /dev/sda5)" --class gnu-linux --class gnu --class os {
	insmod part_msdos
	insmod ext2
	set root='(hd2,msdos2)'
	search --no-floppy --fs-uuid --set=root 20e9f929-3d53-4814-abbd-2e0a38e0eaae
	drivemap -s (hd2) (hd0)
	chainloader +1
}
EOF
COFR

} # mk-sect() -----------------------------------------------------------------



# work definitions

p='pro' 	# for prologu stage
e='epi' 	# for epilogue stage 

echo '### Generating section file >>>>-------------------------' >&2

mk-sect win $e
mk-sect gen $e
