#! /bin/sh
set -e

####################################################
#
# Insert Section in GRUB configuration file
# v.0.5 from 30.12.2012. by aso
#
# -t, --pipline           processing input file (stdin) into stdout output file
# -i, --in-place          processing config file "in place" from stdout; default option
#
####################################################


BEG='BEGIN'
Sec='Section'
gen='gentoo'
win='win'


sysconfdir="/etc"
grub_mkcfg_dir="${sysconfdir}/grub.d"
#grub_mkcfg_dir=''

self=`basename $0`
GRUB_PREFIX=`echo '/boot/grub' | sed "s,//*,/,g"`


pfn='grub.cfg'	# Processing file name
cos=$win

#allopts=''	# list of all unrecognized options
#in_cfg=''	# name if input cfg file
#out_cfg=''	# name of output cfg file
#inplace=''	# flag - in place processing (input == output)


usage () {
    cat <<EOF
Usage: $self [OPTION]
Generate a grub config file

  -t, --pipline           processing input file (stdin) into stdout output file
  -i, --in-place          processing config file "in place" from stdout; default option

Report bugs to <bug-grub@gnu.org>.
EOF
}


# Create marker
mark () {
local MARK='###'
echo "$MARK\ $1\ $MARK"
}


# Generate section file name
# Parameters:
#   #1 - prefix, OS_name (gentoo, win),
#   #2 - tail {prolog | epilog}
sect_fn(){
#echo "$1-sect_$2.cfg"
echo "${grub_mkcfg_dir}/$1-$2.cfg"
}



# Echoing OS name from class
# Parameter:
#   #1 - class OS (gentoo, win),
o_name() {
case "$1" in
'win')	  echo 'Microsoft Windows'
	;;
'gentoo') echo 'Gentoo Linux'
	;;
'gen')	  echo 'Gentoo Linux'
	;;
esac
}


#p='prologue'
p='prolog'
#e='epilogue'
e='epilog'

# Insert section in config file function
# Parameters:
#   $1 - OS class
remark_insert()
{
## control string for sed for search control comment: '### Begin...' & insert file name
echo "
/$(mark "BEGIN\ $(echo $(sect_fn $1 $p)| sed 's/\//\\&/'g)")/ r $(sect_fn $1 $p)
/$(mark "BEGIN\ $(echo $(sect_fn $1 $e)| sed 's/\//\\&/'g)")/ r $(sect_fn $1 $e)
"
} # sect_insert()--------------------------------------------------------------


# Echoing string for varkup section in config file function
# Parameters:
#   $1 - OS class (gentoo, win...)
#   $2 - OS name (ex. 'Microsoft Windows' etc...)
echo_remark()
{

echo "
/\([^#]*.*menuentry\)\([^#].*$(o_name $1)\)/! b end  # detect start of section /menuentry <OS_Name>/

i\\
\\\n$(mark "BEGIN\ $(sect_fn $1 $p)")
i\\$(mark "END\ $(sect_fn $1 $p)")\\\n

:consect		# continue sampling section
n
/^}/! b consect

:interch		# final of section. Sampling iterval between sections
n
/[^#]*.*menuentry/ {	# detect new section
/[^#]*.*$(o_name $1)/ b consect	# new section is desired
b close			# new section is not desired
}
/### \(BEGIN\)\|\(END\)/ b close	# detect new section, marked by control comments
b interch

:close

i\\
\\\n$(mark "BEGIN\ $(sect_fn $1 $e)")
i\\$(mark "END\ $(sect_fn $1 $e)")\\\n

:end
"

} # echo_remark() -------------------------------------------------------------------------



# Processing the arguments.
while test $# -gt 0
do
    option=$1
    shift

    case "$option" in
    -h | --help)
	usage
	exit 2 ;;
    -v | --version)
#	echo "$self (${PACKAGE_NAME}) ${PACKAGE_VERSION}"
	echo "v.0.2.0, 21.12.2012."
	exit 0 ;;
    -t | --pipeline)
	pipe=${option} ;;
    -i | --in-place)
	pipe='' ;;
    -*)
	allopts="$allopts $option"
	;;
    # Explicitly ignore non-option arguments, for compatibility.
    esac
done


if ! [ $pipe ] ; then

#echo "====================================\n\nIn the no pipe" >&2
  tmpbuf='/tmp/$$$sect$$$'
  exec 4<&1
  outfile=$(readlink /proc/self/fd/4)
  exec 4>&- 1>&-	# close stdout & file #4
#ls -l /proc/self/fd >&2
  cp $outfile $tmpbuf
#cat $outfile >&2
  exec 1>${outfile}
#  exec >&4

fi


echo "Sectioning grub.cfg ..." >&2
sect_fn 'win' 'prolog' >&2

#cat $tmpbuf | sed $allopts -e "$(echo_remark $win)" | sed $allopts -e "$(remark_insert $win)" | sed $allopts -e "$(echo_remark $gen)" | sed $allopts -e "$(remark_insert $gen)"
cat $tmpbuf | sed $allopts -e "$(echo_remark $win)" | sed $allopts -e "$(remark_insert $win)" | sed $allopts -e "$(echo_remark $gen)" | sed $allopts -e "$(remark_insert $gen)" >&2
#cat $tmpbuf | sed $allopts -e "$(echo_remark $win)" | sed $allopts -e "$(echo_remark $gen)" >&2
#cat $tmpbuf | sed $allopts -e "$(echo_remark $win)" | sed $allopts -e "$(remark_insert $win)" | sed $allopts -e "$(echo_remark $gen)" >&2
echo "\n\n=============================================" >&2
echo "###### echo_remark $win ######" >&2
echo "$(echo_remark $win)" >&2
echo "\n\n###### remark_insert $win ######" >&2
echo "$(remark_insert $win)" >&2

if ! [ $pipe ] ; then
  rm "$tmpbuf"	# remove tmpbuf
fi
