#! /bin/sh
set -e
####################################################
#
#
# Interactive launch of folding, the grub-mkconfig helper script.
# (c) aso<Solomatov.A.A@gmail.com>, v.2.2.1 by 07.07.2014.							#
#   GPLv3										#
#
# -t, --pipeline,     pipline mode: data from input file (stdin) processed 'on fly'
#     --pipe              and saved into stdout output file (intended for debug)
# -i, --in-place      processing config file "in place" from stdout; default option
# -h, --help              print this message and exit
# -v, --version           print the version information and exit
#
####################################################

inputname='aaa1'

./folding --pipeline < ${inputname} | most
