#! /bin/sh
set -e

## grub-mkconfig helper script.
## Copyright (C) 2006,2007,2008,2009,2010  Free Software Foundation, Inc.
##
## GRUB is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## GRUB is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with GRUB.  If not, see <http://www.gnu.org/licenses/>.
#
#prefix="/usr"
#exec_prefix="${prefix}"
#datarootdir="${prefix}/share"
#
#. "${datarootdir}/grub/grub-mkconfig_lib"
#
#export TEXTDOMAIN=grub
#export TEXTDOMAINDIR="${datarootdir}/locale"

# Don't change the next "if" operator
if test "x${_infolding}" = "x" ; then
  echo "# This is a stub"
  echo "# It's a test version"
  exit
fi


echo "Close Gentoo folding section in menu" >&2

# My insertion - aso
cat << EOF
}
EOF