#! /bin/sh
set -e

## grub-mkconfig helper script.
## Copyright (C) 2006,2007,2008,2009,2010  Free Software Foundation, Inc.
##
## GRUB is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## GRUB is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with GRUB.  If not, see <http://www.gnu.org/licenses/>.

####################################################
#
# MS Windows section epilogue GRUB configuration file
# v.2.0.1 from 17.06.2014. by aso
#
# -i, --insert            insert section data into stdout
# -x, --exclude           exclude folding header
# -h, --help              print this message and exit
# -v, --version           print the version information and exit
#
####################################################

ver='2.0.1'
date='17.06.2014'
version="v.$ver, from $date by aso"


usage()
{
    cat <<EOF
Usage: $self [OPTION]
Insert Folding section in GRUB configuration file

  -i, --insert            output section data into stdout
  -x, --exclude           exclude folding header
  -h, --help              print this message and exit
  -v, --version           print the version information and exit

Combined short options are allowed.
EOF
} # usage() --------------------------------------


_insert=0
_exclude=0

# Processing the arguments.
while test $# -gt 0
do
    option=$1
    shift

    case "$option" in
    -h | --help)
	usage
	exit 2 ;;
    -v | --version)
	echo $version
	exit 1 ;;
    -i | --insert)
	_insert=1
	;;
    -x | --exclude)
	_exclude=1
	;;
    -ix | -xi)
	_insert=1
	_exclude=1
	;;
    -*)
	echo "Unrecognized options: $option"
	;;
    # Explicitly ignore non-option arguments, for compatibility.
    esac
done

# Don't change the next "if" operator
if [ ${_insert} = 0 ] ; then
  echo "# This is a win section epilogue stub"
  echo "# It's a test version,"
  echo "# $version"
  exit
fi


echo "Close Windows folding section in menu" >&2

# User code section 1 >>>------------------------
# Insert user code here, between this lines, code placed in section

# End of user code section <<<-------------------

# Insert Gentoo section footer if nedeed, close the section
if  [ "${_exclude}" = 0 ] ; then
    echo '}'
fi

# User code section 2 >>>------------------------
# Add user code below this line, code placed out of section
