#! /bin/sh
set -e

## grub-mkconfig helper script.
## Copyright (C) 2006,2007,2008,2009,2010  Free Software Foundation, Inc.
##
## GRUB is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## GRUB is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with GRUB.  If not, see <http://www.gnu.org/licenses/>.

####################################################
#
# MS Windows section prologue GRUB configuration file
# v.1.9.1 from 14.06.2014. by aso
#
# -i, --insert            insert section data into stdout
# -x, --exclude           exclude folding header
# -h, --help              print this message and exit
# -v, --version           print the version information and exit
#
####################################################

ver='1.9.1'
date='14.06.2014'
version="v.$ver, from $date by aso"

#
#prefix="/usr"
#exec_prefix="${prefix}"
#datarootdir="${prefix}/share"
#
#. "${datarootdir}/grub/grub-mkconfig_lib"
#
#export TEXTDOMAIN=grub
#export TEXTDOMAINDIR="${datarootdir}/locale"
usage()
{
    cat <<EOF
Usage: $self [OPTION]
Insert Folding section in GRUB configuration file

  -i, --insert            output section data into stdout
  -x, --exclude           exclude folding header
  -h, --help              print this message and exit
  -v, --version           print the version information and exit

Combined short options are allowed.
EOF
} # usage() --------------------------------------

_insert=0
_exclude=0

# Processing the arguments.
while test $# -gt 0
do
    option=$1
    shift

    case "$option" in
    -h | --help)
	usage
	exit 2 ;;
    -v | --version)
	echo $version
	exit 1 ;;
    -i | --insert)
	_insert=1
	;;
    -x | --exclude)
	_exclude=1
	;;
    -ix | -xi)
	_insert=1
	_exclude=1
	;;
    -*)
	echo "Unrecognized options: $option"
	;;
    # Explicitly ignore non-option arguments, for compatibility.
    esac
done


# Don't change the next "if" operator
if [ ${_insert} = 0 ] ; then
  echo "# This is a win section prologue stub"
  echo "# It's a test version,"
  echo "# $version"
  exit
fi


echo "Start Windows folding section in menu" >&2

# User code section 1 >>>------------------------
# Insert user code here, between this lines, code placed out of section, before section header

# End of user code section <<<-------------------

# Insert MS Windows section header if nedeed
if  [ "${_exclude}" = 0 ] ; then
    echo 'submenu "MS Windows (all variants)" {'
fi

# User code section 2 >>>------------------------
# Insert user code below this line, code placed in section after header >>>-----------------

# My insertion - aso
# MS Windows section - native boot through System Commander
cat << EOF
# Custom entry for System Commander launch
menuentry "Microsoft Windows (all variants, on /dev/sdb)" --class windows --class os {
	insmod part_msdos
	insmod ntfs
	set root='(hd1)'
	drivemap (hd0) (hd2)
	drivemap (hd1) (hd0)
	drivemap (hd2) (hd1)
	chainloader +1
}
EOF
